name-template: "{{RELEASE_NAME_TEMPLATE}}"
tag-template: "{{TAG_TEMPLATE}}"

categories:
  - type: pre-exclude
    when:
      labels:
        - skip-changelog
        - chore
        - maintenance
        - ci
        - tests

  - title: "Features"
    semver-increment: minor
    when:
      labels:
        - enhancement
        - feature

  - title: "Bug fixes"
    semver-increment: patch
    when:
      labels:
        - bug
        - fix

  - title: "Documentation"
    semver-increment: patch
    when:
      labels:
        - documentation
        - docs

  - title: "Dependencies"
    semver-increment: patch
    when:
      label: dependencies

  - type: version-resolver
    semver-increment: major
    when:
      label: breaking

  - type: version-resolver
    semver-increment: patch

change-template: "- $TITLE (#$NUMBER) @$AUTHOR <!-- release-draft-sync:pr=$NUMBER -->"
no-changes-template: ""

template: |
  ## Release notes

  $CHANGES
