name: Publish package
on:
  workflow_dispatch:
    inputs:
      package-directory:
        description: Package directory or workspace name
        required: true
        default: packages/my-package
        type: string
      registry:
        description: Package registry
        required: true
        default: all
        type: choice
        options:
          - github
          - npm
          - all
      tag:
        description: npm distribution tag
        required: true
        type: string
permissions:
  contents: write
  packages: write
jobs:
  publish:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_npm-publish.yml@v0.1.0
    with:
      package-directory: ${{ inputs.package-directory }}
      target-branch: main
      registry: ${{ inputs.registry }}
      tag: ${{ inputs.tag }}
      node-version: "24"
    secrets: inherit
