name: Package CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  packages: read
jobs:
  packages:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_package-ci.yml@v0
    with:
      packages-directory: packages
      node-version: "24"
    secrets: inherit
