name: Publish codemod
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Validate without publishing
        required: true
        default: true
        type: boolean
jobs:
  publish:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_codemod-publish.yml@v0
    with:
      target-branch: ${{ github.ref_name }}
      codemod-directory: packages/my-codemod
      dry-run: ${{ inputs.dry-run }}
      node-version: "24"
    secrets: inherit
