name: Example · Reset release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  example:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_reset-release.yml@v0
    with:
      package: '.'
      dry-run: true
