name: Example · Restore release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  example:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_restore-release.yml@main
    with:
      package: '.'
      restore-source: 'tag:v0.1.0'
      dry-run: true
