name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  packages: read
jobs:
  ci:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_node-ci.yml@v0.1.0
    with:
      node-version: "24"
    secrets: inherit
