name: Release Draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: Draft version without the v prefix
        required: true
        type: string

jobs:
  draft:
    permissions:
      contents: write
    uses: moyarich/reusable-workflows/.github/workflows/reusable_release-drafter.yml@v0.1.0
    with:
      target-branch: main
      version: ${{ inputs.version }}
      release-name: My Project v${{ inputs.version }}
      changelog-path: CHANGELOG.md
      dry-run: true
