name: Manage issue dependencies
on:
  workflow_dispatch:
    inputs:
      issue:
        description: Issue number or URL
        required: true
        type: string
      related-issues:
        description: Related issue numbers or URLs, comma-separated
        required: true
        type: string
permissions:
  contents: read
  issues: write
jobs:
  dependencies:
    uses: moyarich/reusable-workflows/.github/workflows/reusable_manage-issue-dependencies.yml@v0.1.0
    with:
      issue: ${{ inputs.issue }}
      relationship: blocked-by
      action: add
      related_issues: ${{ inputs.related-issues }}
      dry_run: false
